# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ui_main(object):
    def setupUi(self, ui_main):
        ui_main.setObjectName("ui_main")
        ui_main.resize(662, 522)
        self.centralwidget = QtWidgets.QWidget(ui_main)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(40, 20))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.com_selete = QtWidgets.QComboBox(self.centralwidget)
        self.com_selete.setMaximumSize(QtCore.QSize(80, 20))
        self.com_selete.setObjectName("com_selete")
        self.com_selete.addItem("")
        self.com_selete.addItem("")
        self.com_selete.addItem("")
        self.com_selete.addItem("")
        self.horizontalLayout.addWidget(self.com_selete)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(40, 20))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.baud_selete = QtWidgets.QComboBox(self.centralwidget)
        self.baud_selete.setMaximumSize(QtCore.QSize(80, 20))
        self.baud_selete.setObjectName("baud_selete")
        self.baud_selete.addItem("")
        self.baud_selete.addItem("")
        self.baud_selete.addItem("")
        self.baud_selete.addItem("")
        self.horizontalLayout_2.addWidget(self.baud_selete)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(40, 20))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.data_bit_selete = QtWidgets.QComboBox(self.centralwidget)
        self.data_bit_selete.setMaximumSize(QtCore.QSize(80, 20))
        self.data_bit_selete.setObjectName("data_bit_selete")
        self.data_bit_selete.addItem("")
        self.data_bit_selete.addItem("")
        self.data_bit_selete.addItem("")
        self.data_bit_selete.addItem("")
        self.horizontalLayout_3.addWidget(self.data_bit_selete)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(40, 20))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.check_bit_selete = QtWidgets.QComboBox(self.centralwidget)
        self.check_bit_selete.setMaximumSize(QtCore.QSize(80, 20))
        self.check_bit_selete.setObjectName("check_bit_selete")
        self.check_bit_selete.addItem("")
        self.check_bit_selete.addItem("")
        self.check_bit_selete.addItem("")
        self.check_bit_selete.addItem("")
        self.check_bit_selete.addItem("")
        self.horizontalLayout_4.addWidget(self.check_bit_selete)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(40, 20))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.stop_bit_selete = QtWidgets.QComboBox(self.centralwidget)
        self.stop_bit_selete.setMaximumSize(QtCore.QSize(80, 20))
        self.stop_bit_selete.setObjectName("stop_bit_selete")
        self.stop_bit_selete.addItem("")
        self.stop_bit_selete.addItem("")
        self.stop_bit_selete.addItem("")
        self.horizontalLayout_5.addWidget(self.stop_bit_selete)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.open_serial = QtWidgets.QPushButton(self.centralwidget)
        self.open_serial.setMaximumSize(QtCore.QSize(120, 20))
        self.open_serial.setObjectName("open_serial")
        self.verticalLayout.addWidget(self.open_serial)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(50, 20))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.counter_rec = QtWidgets.QLabel(self.centralwidget)
        self.counter_rec.setMaximumSize(QtCore.QSize(70, 20))
        self.counter_rec.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.counter_rec.setObjectName("counter_rec")
        self.horizontalLayout_6.addWidget(self.counter_rec, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(50, 20))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.counter_send = QtWidgets.QLabel(self.centralwidget)
        self.counter_send.setMaximumSize(QtCore.QSize(70, 20))
        self.counter_send.setObjectName("counter_send")
        self.horizontalLayout_7.addWidget(self.counter_send, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear.sizePolicy().hasHeightForWidth())
        self.clear.setSizePolicy(sizePolicy)
        self.clear.setMaximumSize(QtCore.QSize(40, 20))
        self.clear.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.clear.setObjectName("clear")
        self.horizontalLayout_8.addWidget(self.clear)
        self.pause_dispaly = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause_dispaly.sizePolicy().hasHeightForWidth())
        self.pause_dispaly.setSizePolicy(sizePolicy)
        self.pause_dispaly.setMaximumSize(QtCore.QSize(80, 20))
        self.pause_dispaly.setObjectName("pause_dispaly")
        self.horizontalLayout_8.addWidget(self.pause_dispaly)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.disp_send = QtWidgets.QCheckBox(self.centralwidget)
        self.disp_send.setMinimumSize(QtCore.QSize(0, 0))
        self.disp_send.setMaximumSize(QtCore.QSize(120, 20))
        self.disp_send.setIconSize(QtCore.QSize(16, 16))
        self.disp_send.setObjectName("disp_send")
        self.verticalLayout_2.addWidget(self.disp_send)
        self.time_stamp = QtWidgets.QCheckBox(self.centralwidget)
        self.time_stamp.setMaximumSize(QtCore.QSize(120, 20))
        self.time_stamp.setObjectName("time_stamp")
        self.verticalLayout_2.addWidget(self.time_stamp)
        self.mask_data_type = QtWidgets.QCheckBox(self.centralwidget)
        self.mask_data_type.setMaximumSize(QtCore.QSize(120, 20))
        self.mask_data_type.setObjectName("mask_data_type")
        self.verticalLayout_2.addWidget(self.mask_data_type)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_14.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_13.addWidget(self.label_8)
        self.hex_display = QtWidgets.QCheckBox(self.centralwidget)
        self.hex_display.setObjectName("hex_display")
        self.horizontalLayout_13.addWidget(self.hex_display)
        self.line_wrap = QtWidgets.QCheckBox(self.centralwidget)
        self.line_wrap.setObjectName("line_wrap")
        self.horizontalLayout_13.addWidget(self.line_wrap)
        self.save_data = QtWidgets.QPushButton(self.centralwidget)
        self.save_data.setObjectName("save_data")
        self.horizontalLayout_13.addWidget(self.save_data)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.keyword = QtWidgets.QLineEdit(self.centralwidget)
        self.keyword.setObjectName("keyword")
        self.horizontalLayout_9.addWidget(self.keyword)
        self.horizontalLayout_9.setStretch(1, 1)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_13.setStretch(4, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.rec_data = QtWidgets.QTextBrowser(self.centralwidget)
        self.rec_data.setObjectName("rec_data")
        self.verticalLayout_6.addWidget(self.rec_data)
        self.horizontalLayout_14.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.timer_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.timer_1.setMaximumSize(QtCore.QSize(45, 20))
        self.timer_1.setAutoFillBackground(False)
        self.timer_1.setObjectName("timer_1")
        self.horizontalLayout_10.addWidget(self.timer_1)
        self.timer_num_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.timer_num_1.setMaximumSize(QtCore.QSize(30, 20))
        self.timer_num_1.setObjectName("timer_num_1")
        self.horizontalLayout_10.addWidget(self.timer_num_1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setMaximumSize(QtCore.QSize(15, 20))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.is_hex_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.is_hex_1.setMaximumSize(QtCore.QSize(40, 20))
        self.is_hex_1.setObjectName("is_hex_1")
        self.horizontalLayout_10.addWidget(self.is_hex_1)
        self.send_1 = QtWidgets.QPushButton(self.centralwidget)
        self.send_1.setMinimumSize(QtCore.QSize(0, 0))
        self.send_1.setMaximumSize(QtCore.QSize(50, 20))
        self.send_1.setObjectName("send_1")
        self.horizontalLayout_10.addWidget(self.send_1)
        self.send_data_1 = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_data_1.sizePolicy().hasHeightForWidth())
        self.send_data_1.setSizePolicy(sizePolicy)
        self.send_data_1.setMinimumSize(QtCore.QSize(0, 15))
        self.send_data_1.setMaximumSize(QtCore.QSize(16777215, 40))
        self.send_data_1.setObjectName("send_data_1")
        self.horizontalLayout_10.addWidget(self.send_data_1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.timer_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.timer_2.setMaximumSize(QtCore.QSize(45, 20))
        self.timer_2.setAutoFillBackground(False)
        self.timer_2.setObjectName("timer_2")
        self.horizontalLayout_12.addWidget(self.timer_2)
        self.timer_num_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.timer_num_2.setMaximumSize(QtCore.QSize(30, 20))
        self.timer_num_2.setObjectName("timer_num_2")
        self.horizontalLayout_12.addWidget(self.timer_num_2)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setMaximumSize(QtCore.QSize(15, 20))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.is_hex_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.is_hex_2.setMaximumSize(QtCore.QSize(40, 20))
        self.is_hex_2.setObjectName("is_hex_2")
        self.horizontalLayout_12.addWidget(self.is_hex_2)
        self.send_2 = QtWidgets.QPushButton(self.centralwidget)
        self.send_2.setMaximumSize(QtCore.QSize(50, 20))
        self.send_2.setObjectName("send_2")
        self.horizontalLayout_12.addWidget(self.send_2)
        self.send_data_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.send_data_2.setMinimumSize(QtCore.QSize(0, 15))
        self.send_data_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.send_data_2.setObjectName("send_data_2")
        self.horizontalLayout_12.addWidget(self.send_data_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.timer_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.timer_3.setMaximumSize(QtCore.QSize(45, 20))
        self.timer_3.setAutoFillBackground(False)
        self.timer_3.setObjectName("timer_3")
        self.horizontalLayout_11.addWidget(self.timer_3)
        self.timer_num_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.timer_num_3.setMaximumSize(QtCore.QSize(30, 20))
        self.timer_num_3.setObjectName("timer_num_3")
        self.horizontalLayout_11.addWidget(self.timer_num_3)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setMaximumSize(QtCore.QSize(15, 20))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.is_hex_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.is_hex_3.setMaximumSize(QtCore.QSize(40, 20))
        self.is_hex_3.setObjectName("is_hex_3")
        self.horizontalLayout_11.addWidget(self.is_hex_3)
        self.send_3 = QtWidgets.QPushButton(self.centralwidget)
        self.send_3.setMaximumSize(QtCore.QSize(50, 20))
        self.send_3.setObjectName("send_3")
        self.horizontalLayout_11.addWidget(self.send_3)
        self.send_data_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.send_data_3.setMinimumSize(QtCore.QSize(0, 15))
        self.send_data_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.send_data_3.setObjectName("send_data_3")
        self.horizontalLayout_11.addWidget(self.send_data_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        ui_main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ui_main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 662, 23))
        self.menubar.setObjectName("menubar")
        ui_main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ui_main)
        self.statusbar.setObjectName("statusbar")
        ui_main.setStatusBar(self.statusbar)

        self.retranslateUi(ui_main)
        QtCore.QMetaObject.connectSlotsByName(ui_main)

    def retranslateUi(self, ui_main):
        _translate = QtCore.QCoreApplication.translate
        ui_main.setWindowTitle(_translate("ui_main", "MainWindow"))
        self.label.setText(_translate("ui_main", "COM 口"))
        self.com_selete.setItemText(0, _translate("ui_main", "COM 3"))
        self.com_selete.setItemText(1, _translate("ui_main", "COM 4"))
        self.com_selete.setItemText(2, _translate("ui_main", "COM 5"))
        self.com_selete.setItemText(3, _translate("ui_main", "COM 6"))
        self.label_2.setText(_translate("ui_main", "波特率"))
        self.baud_selete.setItemText(0, _translate("ui_main", "9600"))
        self.baud_selete.setItemText(1, _translate("ui_main", "19200"))
        self.baud_selete.setItemText(2, _translate("ui_main", "115200"))
        self.baud_selete.setItemText(3, _translate("ui_main", "3000000"))
        self.label_3.setText(_translate("ui_main", "数据位"))
        self.data_bit_selete.setItemText(0, _translate("ui_main", "8"))
        self.data_bit_selete.setItemText(1, _translate("ui_main", "7"))
        self.data_bit_selete.setItemText(2, _translate("ui_main", "6"))
        self.data_bit_selete.setItemText(3, _translate("ui_main", "5"))
        self.label_4.setText(_translate("ui_main", "校验位"))
        self.check_bit_selete.setItemText(0, _translate("ui_main", "N"))
        self.check_bit_selete.setItemText(1, _translate("ui_main", "E"))
        self.check_bit_selete.setItemText(2, _translate("ui_main", "O"))
        self.check_bit_selete.setItemText(3, _translate("ui_main", "S"))
        self.check_bit_selete.setItemText(4, _translate("ui_main", "M"))
        self.label_5.setText(_translate("ui_main", "停止位"))
        self.stop_bit_selete.setItemText(0, _translate("ui_main", "1"))
        self.stop_bit_selete.setItemText(1, _translate("ui_main", "1.5"))
        self.stop_bit_selete.setItemText(2, _translate("ui_main", "2"))
        self.open_serial.setText(_translate("ui_main", "打开串口"))
        self.label_6.setText(_translate("ui_main", "收字节数"))
        self.counter_rec.setText(_translate("ui_main", "0"))
        self.label_7.setText(_translate("ui_main", "发字节数"))
        self.counter_send.setText(_translate("ui_main", "0"))
        self.clear.setText(_translate("ui_main", "清空"))
        self.pause_dispaly.setText(_translate("ui_main", "暂停显示"))
        self.disp_send.setText(_translate("ui_main", "显示发送"))
        self.time_stamp.setText(_translate("ui_main", "时间戳"))
        self.mask_data_type.setText(_translate("ui_main", "标记TX/RX"))
        self.label_8.setText(_translate("ui_main", "接收区"))
        self.hex_display.setText(_translate("ui_main", "hex显示"))
        self.line_wrap.setText(_translate("ui_main", "自动换行"))
        self.save_data.setText(_translate("ui_main", "保存数据"))
        self.label_13.setText(_translate("ui_main", "过滤关键字"))
        self.label_9.setText(_translate("ui_main", "发送区"))
        self.timer_1.setText(_translate("ui_main", "定时"))
        self.timer_num_1.setText(_translate("ui_main", "1000"))
        self.label_10.setText(_translate("ui_main", "ms"))
        self.is_hex_1.setText(_translate("ui_main", "HEX"))
        self.send_1.setText(_translate("ui_main", "发送"))
        self.timer_2.setText(_translate("ui_main", "定时"))
        self.timer_num_2.setText(_translate("ui_main", "1000"))
        self.label_11.setText(_translate("ui_main", "ms"))
        self.is_hex_2.setText(_translate("ui_main", "HEX"))
        self.send_2.setText(_translate("ui_main", "发送"))
        self.timer_3.setText(_translate("ui_main", "定时"))
        self.timer_num_3.setText(_translate("ui_main", "1000"))
        self.label_12.setText(_translate("ui_main", "ms"))
        self.is_hex_3.setText(_translate("ui_main", "HEX"))
        self.send_3.setText(_translate("ui_main", "发送"))
